{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.secretStore (gt (len (keys (.Values.externalSecrets.secretStore.provider | default dict))) 0) }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStore.name | default (printf "%s-store" (include "app-chart.fullname" .)) }}
  labels:
    {{- include "app-chart.labels" . | nindent 4 }}
spec:
  provider:
    {{- toYaml .Values.externalSecrets.secretStore.provider | nindent 4 }}
{{- end }}
